### ISSUE TITLE
Modifying navbar

### ISSUE THREAD

**Issue by saihaj** [primer/doctocat-template#1]
Hey, 
How can I modify the items in the nav bar. I only see that there is `nav.yml` for side navigation but what can I do to modify the top navigation?
<img width="650" alt="image" src="https://user-images.githubusercontent.com/44710980/83981773-9725c200-a8e6-11ea-8a81-8d4b6b50fc85.png">

Update: I see that there is [`primer-nav.yml`](https://github.com/primer/doctocat/blob/master/theme/src/primer-nav.yml) that is being used in [@primer/doctocat](https://github.com/primer/doctocat) for these links:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/44710980/83982312-7ca21780-a8eb-11ea-82c8-8f98da1d6607.png"> 
What can I do in this template to override that config? 

Also how can I modify this part ?
<img width="350" alt="image" src="https://user-images.githubusercontent.com/44710980/83982316-888dd980-a8eb-11ea-8565-83225cc679d0.png">

**Comment by emplums** [comment]
Hey @saihaj you should be able to achieve this via [Component Shadowing](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/)! :)
