### ISSUE TITLE
yarn: Support for the experimental syntax 'logicalAssignment' isn't currently enabled

### ISSUE THREAD

**Issue by Ninroot** [primer/doctocat-template#35]
From a clean repository, `yarn` command fails:

```
Generating development JavaScript bundle failed

/sandbox/node_modules/@primer/gatsby-theme-doctocat/src/components/layout.js: Support for the experimental syntax 'logicalAssignment' isn't currently enabled (24:11):
```

It seems someone created a codesandbox which does exactly what I am doing and fails the same way: https://codesandbox.io/s/gq707

- node v17.3.0
- npm 8.3.0
- macos 12.1

**Comment by mojatter** [comment]
I can fix same issue.

```sh
npm install --save-dev @babel/plugin-proposal-logical-assignment-operators
```

Refer to https://babeljs.io/docs/en/babel-plugin-proposal-logical-assignment-operators

- node v16.16.0
- npm 8.11.0

**Comment by lesliecdubs** [comment]
Thanks for the report! This is likely due to the outstanding dependency upgrades in this repo: https://github.com/primer/doctocat-template/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies. 

We are focused on other priorities in the short term, but if someone would like to review some of those dependency update PRs, we'd be happy to try to take a look and merge them at some point.

**Comment by brionmario** [comment]
> Thanks for the report! This is likely due to the outstanding dependency upgrades in this repo: https://github.com/primer/doctocat-template/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies.
> 
> We are focused on other priorities in the short term, but if someone would like to review some of those dependency update PRs, we'd be happy to try to take a look and merge them at some point.

Hi @lesliecdubs,

Adding `@babel/plugin-proposal-logical-assignment-operators` as a peer dependency as suggested by @mojatter didn't work for me.

Although, extending the babel config adding `@babel/plugin-proposal-logical-assignment-operators` as a `plugin` worked.
I sent a [PR](https://github.com/primer/doctocat-template/pull/41) with the above change. Please review and merge if you think it's appropriate.

I also locally merged the dependedabot PRs and they seems to be fine too 🙂

**Comment by lesliecdubs** [comment]
Thanks for the update @brionmario, and for working on those dependabot upgrades! We appreciate your contributions.

I've tagged in a teammate to review https://github.com/primer/doctocat-template/pull/41.

**Comment by brionmario** [comment]
> Thanks for the update @brionmario, and for working on those dependabot upgrades! We appreciate your contributions.
> 
> I've tagged in a teammate to review #41.

That's Great. Happy to contribute 😊
